### ISSUE TITLE
Variables are not properly highlighted

### ISSUE THREAD

**Issue by ra100** [ra100/vscode-rockstar-language#1]
For example in

```
My world is nothing 
Fire is ice
```

`my world` is highlighted properly as it's common variable
but `Fire` as a proper variable is not highlighted and it should have been, probably the same way/colour as `world`.
Question is, how should `my` be highlighted, it should maybe have the same colour  as `world`, not they have different colours.

**Comment by bolajiscott** [comment]
would love to see how this works

**Comment by ra100** [comment]
@bolajiscott I've found the issue, and fixed it, it was a typo inclu**r**e vs inclu**d**e :D
